name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check codestyle
        run: git ls-files *.{cpp,hpp} | xargs clang-format -i && git diff --exit-code

      - name: Install clang-tidy
        run: sudo apt install clang-tidy

      - name: Install ninja-build
        run: sudo apt install ninja-build

      - name: Configure CMake
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - name: Test
        run: ctest --preset release